# Generated by Django 5.1.2 on 2024-12-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0003_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='lastname',
            new_name='email',
        ),
    ]
