# Generated by Django 5.1.2 on 2024-12-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0004_rename_lastname_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
