# Generated by Django 5.1.2 on 2024-12-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0006_usuario_lastname_alter_login_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
