# Generated by Django 5.1.2 on 2024-12-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0009_rename_date_venda_data_venda_remove_curso_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='estoque',
            new_name='stock',
        ),
    ]
