# Generated by Django 5.1.2 on 2024-12-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0011_rename_data_venda_venda_data_compra_venda_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_compra',
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appHome.usuario'),
        ),
    ]
